name: Compile SpearMint OS ISOs
on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-variants:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [essentials, ultimate]
    steps:
    - name: Checkout Source Code repository
      uses: actions/checkout@v4

    - name: Set up Build Environments
      run: |
        sudo apt-get update
        sudo apt-get install xorriso -y

    - name: Copy Custom Switch Utilities
      run: |
        sudo mkdir -p /usr/local/bin
        sudo cp spearmint-switch.sh /usr/local/bin/spearmint-switch.sh
        sudo chmod +x /usr/local/bin/spearmint-switch.sh
        
        sudo mkdir -p /etc/skel/Desktop
        sudo cp SpearMint-Switch.desktop /etc/skel/Desktop/
        sudo chmod +x /etc/skel/Desktop/SpearMint-Switch.desktop

    - name: Compile Mint-Kali Live Bootable ISO
      run: |
        chmod +x build.sh
        sudo ./build.sh ${{ matrix.variant }}
        mkdir output
        sudo xorrisofs -o output/SpearMint-${{ matrix.variant }}-v1.iso -R -J .
        
    - name: Deploy Compiled OS Variants to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: output/SpearMint-${{ matrix.variant }}-v1.iso
        tag_name: v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
