name: Compile SpearMint OS ISOs
on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-variants:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [essentials, ultimate]
    steps:
    - name: Checkout Source Code repository
      uses: actions/checkout@v4

    - name: Set up Build Environments
      run: |
        sudo apt-get update -y
        sudo apt-get install xorriso -y

    - name: Compile Mint-Kali Live Bootable ISO
      run: |
        chmod +x build.sh
        sudo ./build.sh ${{ matrix.variant }}
        
    - name: Inject Utilities into Build Layout
      run: |
        mkdir -p output_iso/usr/local/bin
        cp spearmint-switch.sh output_iso/usr/local/bin/
        
        mkdir -p output_iso/etc/skel/Desktop
        cp SpearMint-Switch.desktop output_iso/etc/skel/Desktop/
        
        sudo xorrisofs -o SpearMint-${{ matrix.variant }}-v1.iso -R -J output_iso/

    - name: Deploy Compiled OS Variants to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: SpearMint-${{ matrix.variant }}-v1.iso
        tag_name: v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
